### ISSUE TITLE
Ctrl + Shift + I

### ISSUE THREAD

**Issue by coursar** [foxslot/JS_HW_SportmasterBonus#3]
https://github.com/foxslot/JS_HW_SportmasterBonus/blob/58baab0ba50ff04a05522f9f3d02bb0b30fb4696/app.js#L5

**Comment by foxslot** [comment]
@coursar  не совсем понятно про что это замечание

**Comment by foxslot** [comment]
@coursar может вы имели ввиду alt+shift+f для того чтобы пробелы проставились?

**Comment by coursar** [comment]
Да, извиняюсь. На Windows по-другому.

ср, 18 сент. 2019 г., 20:52 foxslot <notifications@github.com>:

**Comment by foxslot** [comment]
https://github.com/foxslot/JS_HW_SportmasterBonus/blob/2e9c7eff7d9885c4af5a9a626e8e74cb32dbcd05/app.js#L5

Fixed in 2e9c7eff7d9885c4af5a9a626e8e74cb32dbcd05
